inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - ./config/initializers/inflections

AllCops:
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true

  # rubocop対象外(リポジトリ毎で調節)
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/**/*"
    - "bin/*"
    - "config/environments/*"
    - "config/initializers/**/*"
    - "config/puma.rb"
    - "public/**/*"
    - "storage/**/*"

  ### ルールのカスタマイズ

# 設定が厳しいので一旦全てfalseにする
Metrics:
  Enabled: false

# デフォルトをダブルクォーテーションに設定
Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

# コントローラ等のモジュールをネストしての宣言
Style/ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さなくても良い
Style/Documentation:
  Enabled: false

# 文字列のfreeze（Ruby3からは自動でfreezeされるので要らない）
Style/FrozenStringLiteralComment:
  Enabled: false

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# シンボルによる配列の%記法のチェック
Style/SymbolArray:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

# describeクラスを使わない
RSpec/DescribedClass:
  Enabled: false

# itブロックの長さを10行に制限
RSpec/ExampleLength:
  Max: 15

# 同じスコープ内で同じ名前のローカル変数を再定義
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'spec/rails_helper.rb'

# ガード節の提案
Style/GuardClause:
  Enabled: false

# ハッシュ値の省略記法を不可
Style/HashSyntax:
  Enabled: false

# mapメソッドの代わりにpluckメソッドを使用することを推奨
Rails/Pluck:
  Enabled: false

# メモ化されたヘルパーメソッドが複数ある場合の警告
RSpec/MultipleMemoizedHelpers:
  Max: 6 