source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.8', '>= 7.0.8.1'

# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# dotenvの読み込み
gem 'dotenv-rails'

# spotify api
# gem 'rspotify'

# redisセッションストア
# gem 'redis-rails'
gem 'redis-actionpack'

# sidekiq
gem 'sidekiq'
gem 'redis' # sidekiqの依存関係

gem 'sidekiq-cron'

# sidekiqの警告からの対応
gem 'base64', '~> 0.2.0'
gem 'mutex_m', '~> 0.2.0'

# Rubyプロセスのメモリ使用量を取得するための軽量なライブラリ(sidekiqのテストジョブ内で使用)
gem 'get_process_mem'

# aws
gem 'aws-sdk-s3'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]

  # rspec
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'rails-controller-testing'

end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem "spring"

  # rubocop
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false

  # bin/rspecコマンドが作成され、起動にspringが使われて速くなる
  gem 'spring-commands-rspec'

end

group :test do
  # sidekiqのテスト用
  # developmentに配置すると、development環境でtesting APIが起動するため、test環境でのみ読み込む
  gem 'rspec-sidekiq', require: false
end

group :production do
  gem 'unicorn'
end
