name: Build React on S3
on:
  push:
    branches: ['main']
    # branches-ignore:
    #   - '**'  # すべてのブランチを無視
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/app/package-lock.json

      - name: Install Dependencies
        run: |
          cd frontend/app
          npm install

      - name: Build
        run: |
          cd frontend/app
          npm run build

      - name: Verify Build Directory
        run: |
          ls -la frontend/app/dist

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 frontend/app/dist s3://$S3_BUCKET_NAME/

      - name: Invalidate CloudFront Cache  # CloudFrontキャッシュを無効化
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          CFID=$(aws cloudfront list-distributions --query "DistributionList.Items[].{Id:Id,Origin:Origins.Items[0].DomainName}[?contains(Origin,'${{ secrets.AWS_S3_BUCKET_NAME }}.s3')].Id" --output text)
          if [ -z "$CFID" ]; then
            echo "Error: CloudFront distribution ID not found."
            exit 1
          fi
          echo "Invalidating CloudFront distribution ID: ${CFID}"
          aws cloudfront create-invalidation --distribution-id ${CFID} --paths "/*"