name: Build React on S3
on:
  push:
    branches: ['main']
    # branches-ignore:
    #   - '**'  # すべてのブランチを無視
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/app/package-lock.json

      - name: Install Dependencies
        run: |
          cd frontend/app
          npm install

      - name: Build
        run: |
          cd frontend/app
          npm run build

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 build s3://$S3_BUCKET_NAME/